version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: apartment_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:123456@db/apartment_management
      SECRET_KEY: your-secret-key-change-in-production
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: